version: "3.8"

services:

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "alembic upgrade heads && uvicorn --host 0.0.0.0 --port 8000 --reload app:app"
